version: '3.8'

services:
  db:
    image: postgres:15
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "${POSTGRES_PORT}:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: always

  web:
    image: python:3.12
    command: >
      sh -c "
      pip install --no-cache-dir -r requirements.txt &&
      python3.12 app/manage.py migrate &&
      python3.12 app/manage.py createsuperuser &&
      python3.12 app/manage.py runserver 0.0.0.0:8000
      "
    volumes:
      - .:/app
    working_dir: /app
    ports:
      - "${DJANGO_PORT}:8000"
    depends_on:
      db:
        condition: service_healthy
    restart: always

volumes:
  postgres_data:
