name: verified
on: [push]
jobs:
  linter:
    name: linter
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Установка Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.10.6
    - name: dependencies
      run: |
        pip install -r requirements.txt
    - name: Flake8
      run: cd app && flake8
  tests:
    name: tests
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Tests
      run:
        cd app && python manage.py test